### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [giovannilupi/dirbrowse#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by giovannilupi** [comment]
Hello @unixorn ,

Thank you for taking a look at this small repo. I am very sorry about the late response, I did not have notifications enabled for issues on GitHub and missed the message, the problem should be fixed now.

I appreciate your suggestion and have added a license file. The code is mostly taken from a plugin already available with ohmyzsh, I just added an option to browse the parent directory (which I find quite useful) and changed the keybinds to my liking. If you like this plugin, you're very much welcome to share it in any way you prefer.

Cheers
